language: clojure
sudo: false
env:
  global:
  - DATABASE_URL="jdbc:mysql://localhost/owntracks_test?user=root"
before_install:
- openssl aes-256-cbc -K $encrypted_0cde95bf033c_key -iv $encrypted_0cde95bf033c_iv
  -in .travis/deploy_key.pem.enc -out .travis/deploy_key.pem -d
after_success:
- lein uberjar
- chmod 600 .travis/deploy_key.pem
- ssh-keyscan -t rsa,dsa,ecdsa,ed25519 -H  -p 1988 penelope.cfrq.net 2>&1 | tee -a
  $HOME/.ssh/known_hosts
- scp -i .travis/deploy_key.pem -P 1988 target/owntracks-receiver.jar travis-ci@penelope.cfrq.net:/var/tmp/owntracks-receiver.jar
- ssh -i .travis/deploy_key.pem -p 1988 travis-ci@penelope.cfrq.net /opt/owntracks-receiver/update-from-travis
